export enum SOCKET_EVENTS {
  SEND_TEXT_MESSAGE = "SEND_TEXT_MESSAGE",
  CREATE_CHATROOM = "CREATE_CHATROOM"
}

export enum SOCKET_EMITS {
  MESSAGE_CREATED = "MESSAGE_CREATED",
  ACK_MESSAGE_CREATED = "ACK_MESSAGE_CREATED",
  NEW_CHAT_ROOM_CREATED = "NEW_CHAT_ROOM_CREATED"
}
