import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import Sidebar from "@/features/sidebar/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {" "}
          <div className="w-full h-screen">
            <div className="hidden lg:block w-full h-full">
              <ResizablePanelGroup
                direction="horizontal"
                className="rounded-lg border w-full "
              >
                <ResizablePanel minSize={15} maxSize={30} defaultSize={20}>
                  <Sidebar />
                </ResizablePanel>
                <ResizableHandle />
                <ResizablePanel defaultSize={80}>{children}</ResizablePanel>
              </ResizablePanelGroup>
            </div>
            <div className="block lg:hidden">
              <Sidebar />
            </div>
          </div>
      </body>
    </html>
  );
}
