import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import Sidebar from "@/features/sidebar/Sidebar";
import { Toaster } from "@/components/ui/sonner";
import findHomeChatsForStore from "@/server/db/findHomeChatsForStore";
import { HomeChatsProvider } from "@/providers/user-store-provider";
import { mapChatsToStore } from "@/server/mappers/mapChatsToStore";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: Move the fetching logic out of the layout, so that the layout is not dynamic

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
