import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import Sidebar from "@/features/sidebar/Sidebar";
import { Toaster } from "@/components/ui/sonner";
import findHomeChatsForStore from "@/server/db/findHomeChatsForStore";
import { HomeChatsProvider } from "@/providers/user-store-provider";
import { mapChatsToStore } from "@/server/mappers/mapChatsToStore";
import { chatMember, chats, contact, db, message, user } from "db";
import { and, eq, ne } from "drizzle-orm";
import { alias } from "drizzle-orm/pg-core";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO: Move the fetching logic out of the layout, so that the layout is not dynamic

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth.api.getSession({ headers: await headers() });
  if (!session?.user) return;
  console.log(session.user.id);

  console.log("LAYOUT_CHANGED");
  const homeChats = await findHomeChatsForStore(session.user.id);

  console.log("HOMECHATS: ", homeChats);

  const { mappedUsers, mappedChatInfo } = mapChatsToStore(homeChats);

  console.log("mapped: ", mappedChatInfo, mappedUsers);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        <HomeChatsProvider chats={mappedChatInfo} users={mappedUsers}>
          <div className="w-full h-screen">
            <div className=" w-full h-full">
              <ResizablePanelGroup
                direction="horizontal"
                className="rounded-lg border w-full "
              >
                <ResizablePanel minSize={15} maxSize={30} defaultSize={20}>
                  <Sidebar />
                </ResizablePanel>
                <ResizableHandle />
                <ResizablePanel className="hidden lg:block" defaultSize={80}>
                  {children}
                </ResizablePanel>
              </ResizablePanelGroup>
            </div>
          </div>
          <Toaster position="top-center" />
        </HomeChatsProvider>
      </body>
    </html>
  );
}
