export const ClientToServerEvents = {
  SEND_TEXT_MESSAGE: "SEND_TEXT_MESSAGE",
  CREATE_CHATROOM: "CREATE_CHATROOM",
  DELETE_CHATROOM: "DELETE_CHATROOM",
} as const;

export const ServerToClientEvents = {
  MESSAGE_CREATED: "MESSAGE_CREATED",
  ACK_MESSAGE_CREATED: "ACK_MESSAGE_CREATED",
  NEW_CHAT_ROOM_CREATED: "NEW_CHAT_ROOM_CREATED",
  CHATROOM_DELETED: "CHATROOM_DELETED",
} as const;

export const ServerToClientErrors = {
  CHAT_CREATION_FAILED: "CHAT_CREATION_FAILED",
  MESSAGE_CREATION_ERROR: "MESSAGE_CREATION_ERROR",
  CHAT_DELETION_FAILED: "CHAT_DELETION_FAILED",
} as const;

export type ErrorPayload<T> = {
  code: string;
  message: string;
  data: T
}

